config/routes.rb
Rails.application.routes.draw do

  get 'events/success' => 'events#success_index', as: :success_index
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :events, :only => [:index, :create, :new, :edit, :update, :show, :join] do
    resources :epictures, :only => :create
    resources :teams do
      resources :positions do
        resources :memberships, :only => :update
      end
  end
  end
  get 'events/:id/join' => 'events#join', as: :join

  
  
  resources :users, :only => [:show]

  root 'welcome#index'

end

app/models/epicture.rb
class Epicture < ActiveRecord::Base
	belongs_to :event

	has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/


end

app/models/event.rb
class Event < ActiveRecord::Base
	acts_as_taggable
	acts_as_taggable_on :categories

	has_many :epictures
	has_many :memberships
	has_many :users, :through => :memberships

	has_many :teams
	belongs_to :admin, :class_name => "User"


	has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  	after_create :send_event_create_email

  	def self.filter(query, field)
  		if field == "category"
  			query.blank? ? Event.all : Event.tagged_with("#{query}")
  		else 
			query.blank? ? Event.all : Event.where("#{field} LIKE '%#{query}%'")
		end
	
	end

  	protected
		def send_event_create_email
			UserMailer.event_created_email(self).deliver
		end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
	belongs_to :user
	belongs_to :event
	belongs_to :team
	belongs_to :position
	
end

app/models/position.rb
class Position < ActiveRecord::Base
	has_many :memberships
	belongs_to :team


end

app/models/team.rb
class Team < ActiveRecord::Base
	has_many :memberships
	belongs_to :event
	has_many :positions
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
	# has_and_belongs_to_many(:events, :join_table => "users_events")
	acts_as_taggable
	acts_as_taggable_on :categories, :interests


	has_many :memberships
	
	has_many :events, :through => :memberships
	has_many :teams, :through => :memberships
	has_many :positions, :through => :memberships
	
	has_many :created_events, :class_name => 'Event', :foreign_key => :admin_id

	after_create :send_user_create_email

	def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(name:auth.extra.raw_info.name,
                            provider:auth.provider,
                            uid:auth.uid,
                            email:auth.info.email,
                            password:Devise.friendly_token[0,20],
                          )
      end    end
  end

  def profile_pic
    if self.provider == "facebook" && self.uid
      "http://graph.facebook.com/#{self.uid}/picture?type=large"
    end
  end

	protected
		def send_user_create_email
			UserMailer.user_created_email(self).deliver
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?
	
	protected


    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :name, :city, :state, :bio) }
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :name, :city, :state, :bio, :current_password, :interest_list, :category_list) }
    end
    
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/epictures_controller.rb
class EpicturesController < ApplicationController

	def create

		@event = Event.find(params[:event_id])
		@epicture = Epicture.new(:picture => params[:event][:picture])
		@epicture.save
		@event.epictures << @epicture
		redirect_to events_path
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :authenticate_user!, only: [:create, :join, :edit, :update, :new]
	before_action :set_event, only: [:edit, :update, :show, :join]

	def new
		@event = Event.new
	end

	def create

		@event = Event.new(event_params.merge({:admin_id => current_user.id}))
		@event.status = 0
		if @event.save
			#current_user.events << @event
			redirect_to event_path(@event)
		else
			render :new
		end
	end

	def edit
  	end

  	def show
  		
  	
  	end



  	def success_index
  		@events = Event.where(:status => 1)
  	end

  	def join
  		@event.users << current_user
  		redirect_to @event
  	end

  	def update 

  		#check for completion call
  		if params[:status] 
  			@event.update(:status => params[:status])

  		#otherwise it is a normal edit
  		else
  			@event.update(event_params)
  		end

  		#return to that event
  		redirect_to @event
  	end

	def index
		@events = Event.filter(params[:q], params[:field])
		if request.xhr? 
      		render :partial => 'events', :layout => nil
    	end
	end

	private

		def set_event
			@event = Event.find(params[:id])
		end

		def event_params
			params.require(:event).permit(:title, :description, :city, :state, :address, :event_time, :picture, :category_list, :status)
		end

		
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
	before_action :set_membership, :only => [:update, :edit, :show]
	
	def edit
	end

	def show

	end

	def update
		@membership.update(membership_params)
		redirect_to :back
	end

	def set_membership
			@membership = Membership.find(params[:id])
	end

	def membership_params
			params.permit(:event_id, :team_id, :position_id, :membership_id)
	end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController   
def facebook     
     @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)      
     if @user.persisted?       
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	before_action :set_user, only: [:show]

	def show


	end

	private

		def set_user
			@user = User.find(params[:id])
		end

		def event_params
			params.require(:user).permit(:name, :bio, :city, :state, :interest_list, :category_list)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_events.html.erb
<div id="eventslist">
	<div class="row">
		<% @events.each do |event| %>
		
		<div class="col-md-4">
			<div class="event-pic-wrapper">
				<%= link_to image_tag(event.picture, :size => '300x200'), event_path(event) %>
				<div id="events-event-label"><%= event.title %></div>
			</div>
		</div>
		<% end %>
	</div>
</div>	

app/views/events/_navbar.html.erb
<% if user_signed_in? %>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="nav-wrapper">
		<ul class="navbar-right">
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" id="toggle-welcome"><%= "Welcome, #{current_user.name}!" %> <span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu">
					<li><%= link_to "View Profile", user_path(current_user) %></li>
					<li><%= link_to "Edit Profile", edit_user_registration_path %></li>
					<li class="divider"></li>
					<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
				</ul>
			</li>
			<script type="text/javascript">$('.dropdown-toggle').dropdown()</script>
		</ul>
		<ul class="navbar-left">
			<li class="active" id="createeventbutton"><%= link_to image_tag("createeventbutton.png", height: 50, width: 95, id: "createeventbutton"), new_event_path %></li>
			<li class="active" id="findeventbutton"><%= link_to image_tag("findeventbutton.png", height: 50, width: 100, id: "findeventbutton"), events_path %></li>
			<li class="active" id="logo"><%= link_to image_tag("weact.jpg", height: 80, width: 180, id: "logo"), root_path %></li>
		</ul>
	</div>
</nav>
<%else%>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="nav-wrapper">
		<ul class="navbar-right">
			<li class="active" id="signup"><%= link_to "Sign up", new_user_registration_path %></li>
			<li class="active" id="login"><%= link_to "Login", new_user_session_path %></li>
		</ul>
		<ul class="navbar-left">
			<li class="active" id="createeventbutton"><%= link_to image_tag("createeventbutton.png", height: 50, width: 95, id: "createeventbutton"), new_event_path %></li>
			<li class="active" id="findeventbutton"><%= link_to image_tag("findeventbutton.png", height: 50, width: 100, id: "findeventbutton"), events_path %></li>
			<li class="active" id="logo"><%= link_to image_tag("weact.jpg", height: 80, width: 180, id: "logo"), root_path %></li>
		</ul>
	</div>
</nav>
<%end%>

app/views/events/edit.html.erb
<h1>Editing Events</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="events-content">
	<div id="events-shovel-pic">
	</div>
	<div class="events-searchbar">
		<div id="search-label"><%= image_tag("searchicon.png", :size => "20x20") %> Search Events:</div>
		<%= form_tag "/events", method: 'GET', id: 'events_search' do %>
		 	<%= text_field_tag 'q', params[:q] %>
		 	<%= select_tag 'field', options_for_select([ ["Location", "city"], ["Category", "category"], ["Event Title", "title"] ]) %>
		  <div style="clear: both"></div>
		<% end %>
	</div>

	<div id="events">
	  <%= render "events" %>
	</div>

	<% if user_signed_in? %>
		<%= link_to 'Update Account', edit_user_registration_path %>
		<%= link_to 'Stories', success_index_path %>
	<%end%>
</div>

app/views/events/new.html.erb
<h1>Create Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<% if @event.status == 1 %>
	<div class="event-show-view">
		<div class="row">
			<div id="event-show-title">
				<%= @event.title %>
			</div>
			<div class="col-md-4">
				<div class="event-show-image">
					<%= image_tag @event.picture, :size => "400x250" %>
				</div>
				
				<div id="join-event-button">
					This event is over!
				</div>
				<div class="event-show-attributes">
					<div id="attribute-description">Description:</div>
					<%= @event.description %>

					<hr style="background-color:black; border:0; height:1px" />

					<table>
						<tr>
							<td><div id="attribute-city">City:</div></td>
							<td><%= @event.city %></td>

							<td><div id="attribute-state">State:</div></td>
							<td><%= @event.state %></td>
						</tr>
					</table>
					<hr style="background-color:black; border:0; height:1px" />

					<div id="attribute-address">Address:</div>
					<%= @event.address %>
				</div>
			</div>
		<div class="col-md-6">
			<div class="event-structure-header">
				<p>Event Structure<p>
			</div>	

			<div class="event-team-positions">
					<%= high_chart("some_id", @chart) %>
					</div>	
				</div>
			</div>
		</div>
	<p>
		<strong>Upload Pic:</strong>
		<%= form_for(@event, :url => event_epictures_path(@event), :html => { :multipart => true }, method: 'post') do |f| %><%= f.label :picture %>:
	  <%= f.file_field :picture %><%= f.submit("Upload")%><%end%>

	</p>

	<p>
		<strong>Pics:</strong>
		<% @event.epictures.each do |pic| %>
		<%= image_tag pic.picture.url() %>
		<%end%>
	</p>

	<!-- <p><%= form_tag(event_path(@event, :status => 1), method: "patch") do %><%= submit_tag("Complete")%><%end%></p>
	<%= link_to 'Back', events_path %> -->
<%else%>
	<div class="event-show-view">
		<div class="row">
			<div id="event-show-title">
				<%= @event.title %>
			</div>
			<div class="col-md-4">
				<div class="event-show-image">
					<%= image_tag @event.picture, :size => "400x250" %>
				</div>
				
				<div id="join-event-button">
					<% if @event.users.include?(current_user) %>
					You are a member of this event!
					
					<%else%>
					<%= link_to "+ Join Event", join_url(id: @event.id) %>
					<%end%>
				</div>
				<div class="event-show-attributes">
					<div id="attribute-description">Description:</div>
					<%= @event.description %>

					<hr style="background-color:black; border:0; height:1px" />

					<table>
						<tr>
							<td><div id="attribute-city">City:</div></td>
							<td><%= @event.city %></td>

							<td><div id="attribute-state">State:</div></td>
							<td><%= @event.state %></td>
						</tr>
					</table>
					<hr style="background-color:black; border:0; height:1px" />

					<div id="attribute-address">Address:</div>
					<%= @event.address %>
				</div>
			</div>
		<div class="col-md-6">
			<div class="event-structure-header">
				<p>Event Structure<p>
			</div>	

			<div class="event-team-positions">
					<% @event.teams.each do |team| %>
						
							Team: <%= team.name %>
							<br />
							Positions: <br /><% team.positions.each do |position| %>
							<%= position.name %>
							<% if @event.users.include?(current_user) %>
							<% if current_user.positions.include?(position) %>
							<br/>
							You are signed up as <%= position.name %>!
							<br/>
							<%else%>
							<%= form_tag(event_team_position_membership_path(@event, team, position, current_user.memberships.where(:event => @event)[0].id), method: "patch") do %><%= submit_tag("Join")%>
							<%end%>
							<%end%>
							<% end %>
						<% end %>
						<br/>
					<% end %>
					</div>	
				</div>
			</div>
		</div>
<%end%>

app/views/events/success_index.html.erb
<div class="events-content">
	<div id="events-success-pic">
		<h1>Success Stories</h1>
	</div>
	<!-- <div class="events-searchbar">
		<div id="search-label"><%= image_tag("searchicon.png", :size => "20x20") %> Search Events:</div>
		<%= form_tag "/events", method: 'GET', id: 'events_search' do %>
		 	<%= text_field_tag 'q', params[:q] %>
		  <div style="clear: both"></div>
		<% end %>
	</div> -->

	<hr/>

	<div id="events">
	  <%= render "events" %>
	</div>

	<% if user_signed_in? %>
		</br>
		<%= link_to 'Create Event', new_event_path %>
		<br/>

		<%= link_to 'View Profile', user_path(current_user) %>
		<br/>
		<%= link_to 'Update Account', edit_user_registration_path %>
		<%= link_to 'Stories', success_index_path %>
	<%end%>
</div>

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="nav-wrapper">
		<ul class="navbar-right">
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" id="toggle-welcome"><%= "Welcome, #{current_user.name}!" %> <span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu">
					<li><%= link_to "View Profile", user_path(current_user) %></li>
					<li><%= link_to "Edit Profile", edit_user_registration_path %></li>
					<li class="divider"></li>
					<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
				</ul>
			</li>
			<script type="text/javascript">$('.dropdown-toggle').dropdown()</script>
		</ul>
		<ul class="navbar-left">
			<li class="active" id="createeventbutton"><%= link_to image_tag("createeventbutton.png", height: 50, width: 95, id: "createeventbutton"), new_event_path %></li>
			<li class="active" id="findeventbutton"><%= link_to image_tag("findeventbutton.png", height: 50, width: 100, id: "findeventbutton"), events_path %></li>
			<li class="active" id="logo"><%= link_to image_tag("weact.jpg", height: 80, width: 180, id: "logo"), root_path %></li>
		</ul>
	</div>
</nav>
<%else%>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="nav-wrapper">
		<ul class="navbar-right">
			<li class="active" id="signup"><%= link_to "Sign up", new_user_registration_path %></li>
			<li class="active" id="login"><%= link_to "Login", new_user_session_path %></li>
		</ul>
		<ul class="navbar-left">
			<li class="active" id="createeventbutton"><%= link_to image_tag("createeventbutton.png", height: 50, width: 95, id: "createeventbutton"), new_event_path %></li>
			<li class="active" id="findeventbutton"><%= link_to image_tag("findeventbutton.png", height: 50, width: 100, id: "findeventbutton"), events_path %></li>
			<li class="active" id="logo"><%= link_to image_tag("weact.jpg", height: 80, width: 180, id: "logo"), root_path %></li>
		</ul>
	</div>
</nav>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>WeAct</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<link rel="shortcut icon" href="favicon.ico"/>
	</head>
	<body>
	<%= render 'navbar' %>
		<%= yield %>
	</body>
</html>

app/views/users/_navbar.html.erb
<% if user_signed_in? %>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="nav-wrapper">
		<ul class="navbar-right">
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" id="toggle-welcome"><%= "Welcome, #{current_user.name}!" %> <span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu">
					<li><%= link_to "View Profile", user_path(current_user) %></li>
					<li><%= link_to "Edit Profile", edit_user_registration_path %></li>
					<li class="divider"></li>
					<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
				</ul>
			</li>
			<script type="text/javascript">$('.dropdown-toggle').dropdown()</script>
		</ul>
		<ul class="navbar-left">
			<li class="active" id="createeventbutton"><%= link_to image_tag("createeventbutton.png", height: 50, width: 95, id: "createeventbutton"), new_event_path %></li>
			<li class="active" id="findeventbutton"><%= link_to image_tag("findeventbutton.png", height: 50, width: 100, id: "findeventbutton"), events_path %></li>
			<li class="active" id="logo"><%= link_to image_tag("weact.jpg", height: 80, width: 180, id: "logo"), root_path %></li>
		</ul>
	</div>
</nav>
<%else%>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="nav-wrapper">
		<ul class="navbar-right">
			<li class="active" id="signup"><%= link_to "Sign up", new_user_registration_path %></li>
			<li class="active" id="login"><%= link_to "Login", new_user_session_path %></li>
		</ul>
		<ul class="navbar-left">
			<li class="active" id="createeventbutton"><%= link_to image_tag("createeventbutton.png", height: 50, width: 95, id: "createeventbutton"), new_event_path %></li>
			<li class="active" id="findeventbutton"><%= link_to image_tag("findeventbutton.png", height: 50, width: 100, id: "findeventbutton"), events_path %></li>
			<li class="active" id="logo"><%= link_to image_tag("weact.jpg", height: 80, width: 180, id: "logo"), root_path %></li>
		</ul>
	</div>
</nav>
<%end%>

app/views/users/show.html.erb
<h1>Welcome to Your Profile!</h1>

<p><%=@user.name%></p>
<p><%=@user.bio%></p>
<p><%=@user.city%></p>
<p><%=@user.state%></p>
<% if @user.profile_pic %>
  <%=image_tag @user.profile_pic %>
<% end %>

<p>Your Created Events:</p>
<% if @user.created_events.size > 0 %>
<% @user.created_events.each do |event| %>
<li><%= link_to event.title, event_path(event) %></li>
<%end%>
<% else %>

Looks like you haven't created any events yet <%= link_to 'Create Event!', new_event_path %>

<% end %>

<p>Your Joined Events:</p>
<% if @user.events.size > 0 %>
<% @user.events.each do |event| %>
<li><%= link_to event.title, event_path(event) %></li>

<% @user.memberships.each do |membership| %>
	<% if membership.event == event %>
		<% if membership.position %>
			Position: <%= membership.position.name %>, Team: <%= membership.position.team.name %>
			<%end%>
		<%end%>
	<%end%>
<%end%>
<%else%>
Looks like you haven't joined any events <%= link_to 'View Events Now', events_path %>
<%end%>

<p>Your Interests</p>
Personal:<% @user.interest_list.each do |interest| %>
<%= interest %>
<%end%>
<br/>
Event Categories:<%@user.category_list.each do |category| %>
<%= category %>
<%end%>


<br/>
<%= link_to 'View All Events', events_path %>
</br>
<%= link_to 'Update Account', edit_user_registration_path %>
<%= link_to 'Sign Out', destroy_user_session_path, :method => :delete  %>

app/views/welcome/_navbar.html.erb
<% if user_signed_in? %>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="nav-wrapper">
		<ul class="navbar-right">
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" id="toggle-welcome"><%= "Welcome, #{current_user.name}!" %> <span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu">
					<li><%= link_to "View Profile", user_path(current_user) %></li>
					<li><%= link_to "Edit Profile", edit_user_registration_path %></li>
					<li class="divider"></li>
					<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
				</ul>
			</li>
			<script type="text/javascript">$('.dropdown-toggle').dropdown()</script>
		</ul>
		<ul class="navbar-left">
			<li class="active" id="createeventbutton"><%= link_to image_tag("createeventbutton.png", height: 50, width: 95, id: "createeventbutton"), new_event_path %></li>
			<li class="active" id="findeventbutton"><%= link_to image_tag("findeventbutton.png", height: 50, width: 100, id: "findeventbutton"), events_path %></li>
			<li class="active" id="logo"><%= link_to image_tag("weact.jpg", height: 80, width: 180, id: "logo"), root_path %></li>
		</ul>
	</div>
</nav>
<%else%>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="nav-wrapper">
		<ul class="navbar-right">
			<li class="active" id="signup"><%= link_to "Sign up", new_user_registration_path %></li>
			<li class="active" id="login"><%= link_to "Login", new_user_session_path %></li>
		</ul>
		<ul class="navbar-left">
			<li class="active" id="createeventbutton"><%= link_to image_tag("createeventbutton.png", height: 50, width: 95, id: "createeventbutton"), new_event_path %></li>
			<li class="active" id="findeventbutton"><%= link_to image_tag("findeventbutton.png", height: 50, width: 100, id: "findeventbutton"), events_path %></li>
			<li class="active" id="logo"><%= link_to image_tag("weact.jpg", height: 80, width: 180, id: "logo"), root_path %></li>
		</ul>
	</div>
</nav>
<%end%>

app/views/welcome/index.html.erb
<div id="home">
	<div id="hometext">
		<a href="#abouttop" id="learnmore"><%= image_tag('seeforyourself.png', id: "seeforyourself", height: 180, width: 290)%></a>
	</div>
</div>
<a id="abouttop"></a>

<div id="about">
	<div id="backgroundcolor">
		<div class="about-content">
			<h1 class="mission-statement" id="mission-statement">We strive to <strong>strengthen</strong> community bonds through activism at a grassroots level.</h1>
			<!-- <div id="front-page-picture">
					<%= image_tag("houseicon.png", id: "houseicon", height: 80, width: 80) %>
					<%= image_tag("line.png", id: "line", height: 15, width: 270) %>
					<%= image_tag("noteicon.png", id: "noteicon", height: 70, width: 70) %>
					<%= image_tag("line.png", id: "line2", height: 15, width: 270) %>
					<%= image_tag("action.png", id: "actionicon", height: 70, width: 70) %>
			</div> -->
			<div class="row">
				<div class="col-md-4">
					<div class="fp-about-icons"><%= image_tag("houseicon.png", id: "houseicon", height: 80, width: 80) %></div>
					<h3 class="fp-about-headers" id="left-header">Localized Events</h3>
					<p class="fp-paragraphs" id="leftparagraph">
					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
					</p>
				</div>
				<div class="col-md-4">
					<div class="fp-about-icons"><%= image_tag("noteicon.png", id: "noteicon", height: 70, width: 70) %></div>
					<h3 class="fp-about-headers" id="mid-header">Issue Driven</h3>
					<p class="fp-paragraphs" id="midparagraph">
					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
					</p>
				</div>
				<div class="col-md-4">
					<div class="fp-about-icons"><%= image_tag("action.png", id: "actionicon", height: 70, width: 70) %></div>
					<h3 class="fp-about-headers" id="right-header">Take Action</h3>
					<p class="fp-paragraphs" id="rightparagraph">
					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
					</p>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- <a id="signuptop"></a>
		<div id="signup">
		<div id="signupform">
			<%= form_for(:user, :url => session_path(:user)) do |f| %>
			Email:<%= f.text_field :email %>
			Password:<%= f.password_field :password %>
			<%= f.check_box :remember_me %>
			<%= f.label :remember_me %>
			<%= f.submit 'Sign in' %>
			<%= link_to "Forgot your password?", new_password_path(:user) %>
			<% end %>
		</div>
		</div> -->
</body>
</html>